### ISSUE TITLE
偵測的問題QQ

### ISSUE THREAD

**Issue by Howlo123** [lmly9193/MapleStory-Launcher#1]
關於他Case 1偵測的點是偵測甚麼 測試了一下 發現他一直偵測到我Case 1導致無法顯示成正常QQ 大大可以解答嗎

**Comment by lmly9193** [comment]
有圖片嗎?

**Comment by Howlo123** [comment]
將IP改過後 他會顯示維修中 沒辦法偵測到正常 可以指教是他還有神麼東西沒偵測到ㄇQQ

**Comment by lmly9193** [comment]
這用 Autoi t寫的，改完 IP 還有 Port 記得編譯，Code Review 一下應該就知道了。
`
  If @error Then
    $iError = @error
      GUICtrlSetColor($Label1,$COLOR_RED)
      GUICtrlSetState($Button1,$GUI_DISABLE)
      Switch $iError
        Case -2
          Return "維修中"
        Case 1
          Return "維修中"
        Case 2
          Return "維修中"
        Case 10060
          Return "關閉"
      EndSwitch
  Else
    GUICtrlSetColor($Label1,$COLOR_GREEN)
    Return "正常"
  EndIf
`
這裡針測錯誤就有三個選項，建議你改一下三個 Return 看是卡在哪裡問題，在自己上 Autoit 官方說明網頁，看針對哪個除錯。

**Comment by Howlo123** [comment]
是的 我是用Autoi 3編譯的 我卡在的問題是出錯在Case 1 Return "維修中" 
><!! 大大這個真的很棒

**Comment by Howlo123** [comment]
有看明白偵測 但不明白他這段偵測哪裡

**Comment by lmly9193** [comment]
有點時間沒用 Autoit 了一時也找不太到相關資訊。
case 1 是 IP 錯誤，case 2 是 Port 錯誤。我是不清楚你 Code 什麼，但是你通道沒做好也會很難偵錯，建議你先 Ping 一下你自己的 IP 有沒有什麼問題，Internet 自架的話 NAT 沒做當然也找不到。

**Comment by Howlo123** [comment]
好的 那l大 那個內容的文字我該怎麼丟到github中才能讓他讀取 
似乎是要讓他下載...對github特陌生

**Comment by lmly9193** [comment]
自己去查閱一下 Github Page
